#!/usr/bin/env bash
set -euo pipefail

# Use GNU timeout if available; on macOS prefer gtimeout (coreutils)
TIMEOUT_BIN="${TIMEOUT_BIN:-timeout}"
command -v "$TIMEOUT_BIN" >/dev/null 2>&1 || TIMEOUT_BIN="gtimeout"
if ! command -v "$TIMEOUT_BIN" >/dev/null 2>&1; then
  echo "warning: timeout/gtimeout not found; running without a time limit" >&2
  TIMEOUT_BIN=""
fi

file_list=(
    Defs.lean
    Zaux.lean
    Raux.lean
    Digits.lean
    Float_prop.lean
    Round_pred.lean
    Generic_fmt.lean
    Round_generic.lean
    Round_NE.lean
    FIX.lean
    FLT.lean
    FLX.lean
    FTZ.lean
    Ulp.lean
)


# Build the multi-line prompt literally, no expansions.
# NOTE: The line with EOF must be at column 1 with no trailing spaces/tabs.
# The '|| true' prevents 'set -e' from exiting because read -d '' returns 1 at EOF.
for file in "${file_list[@]}"; do
IFS= read -r -d '' msg <<'EOF' || true
Please ensure your implementation Always Works™ for:

## Task: Introduce Missing Theorems in FloatSpec/src/Core/${file}

## Scope

Introduce missing theorems in the file. You can find the record of missing theorems in file /Users/louhantao/Desktop/code/semester_6.5/FloatSpec/FloatSpec/src/Core/Core_Theorems_Comparison.md, which is generated by comparing the Coq and Lean versions of the file. For all the missing theorems in the file, find their corresponding Coq implementation in /Users/louhantao/Desktop/code/semester_6.5/flocq/src/Core and implement them in Lean, using the same name and similar syntax with existing theorems. Leave the proofs empty for now.

### Prerequisites

1. **Read documentation first:**
    - FloatSpec/PIPELINE.md - understand the overall pipeline
    - ./CLAUDE.md - focus on proof writing instructions and mvcgen info

### Core Requirements

### Theorem Importing Process

1. **Follow the Zfast_div_eucl_spec example** in Zaux.lean and other theorems in current file as your template
2. **ONE-BY-ONE approach is mandatory:**
    - Write ONE theorem
    - Use the hoare triple syntax (introduced in FloatSpec/PIPELINE.md and CLAUDE.md) to write the theorem
    - Check immediately with mcp tool or `lake build`
    - Fix any errors before proceeding to next theorem
    - Never batch multiple theorems without checking
3. After writing each theorem, check whether they are aligned with the Coq implementation. If so, mark them as complete in the record file.

### Before Writing Each Theorem

1. **Verify function implementation** - ensure the function body is correct
2. **Preserve syntax** - do NOT change hoare triple syntax unless absolutely necessary
    - Think multiple times before modifying specs or code body
    - If changes are needed, decompose complex specs rather than rewriting

### Compilation Verification

- **After EVERY theorem:** Run `mcp` (preferred) or `lake build xxx`
- **Definition of complete:** NO errors or 'pure true' statements
- **Never mark as complete if:**
    - Any errors or 'pure true' statements remain
    - Compilation returns errors
    - Sorry is allowed, but only as a placeholder for the proof


### Important Notes

- Use MCP tool instead of bash command to get diagnostic messages!
- Skip already-imported theorems!! There might be warnings be just leave them there!
- You can use exisiting (and proved) theorem to assist your spec writing. If a theorem is necessary but not introduced, you can turn to work on that first. The useful theorems might not be in the same file, but in the import list
- When you are trying to use a certain lemma, check through mcp tools (or https://github.com/leanprover-community/mathlib4) to make sure the lemma exists. Else, write your own implementation of the lemma.

### Success Criteria

✅ All error and 'pure true' statements eliminated
✅ Clean compilation for entire file
✅ Each theorem verified individually before moving on
EOF

log_name=/Users/louhantao/Desktop/code/semester_6.5/FloatSpec/.log/codex_log/import_missing_theorems_${file}_round_1.log
# Build the CLI command as an array to preserve spaces/newlines
codex exec "$msg" --dangerously-bypass-approvals-and-sandbox | tee "$log_name"

done

for file in "${file_list[@]}"; do
IFS= read -r -d '' msg <<'EOF' || true
Please ensure your implementation Always Works™ for:

## Task: Introduce Missing Theorems in FloatSpec/src/Core/${file}

## Scope

Introduce missing theorems in the file. You can find the record of missing theorems in file /Users/louhantao/Desktop/code/semester_6.5/FloatSpec/FloatSpec/src/Core/Core_Theorems_Comparison.md, which is generated by comparing the Coq and Lean versions of the file. For all the missing theorems in the file, find their corresponding Coq implementation in /Users/louhantao/Desktop/code/semester_6.5/flocq/src/Core and implement them in Lean, using the same name and similar syntax with existing theorems. Leave the proofs empty for now.

### Prerequisites

1. **Read documentation first:**
    - FloatSpec/PIPELINE.md - understand the overall pipeline
    - ./CLAUDE.md - focus on proof writing instructions and mvcgen info

### Core Requirements

### Theorem Importing Process

1. **Follow the Zfast_div_eucl_spec example** in Zaux.lean and other theorems in current file as your template
2. **ONE-BY-ONE approach is mandatory:**
    - Write ONE theorem
    - Use the hoare triple syntax (introduced in FloatSpec/PIPELINE.md and CLAUDE.md) to write the theorem
    - Check immediately with mcp tool or `lake build`
    - Fix any errors before proceeding to next theorem
    - Never batch multiple theorems without checking
3. After writing each theorem, check whether they are aligned with the Coq implementation. If so, mark them as complete in the record file.

### Before Writing Each Theorem

1. **Verify function implementation** - ensure the function body is correct
2. **Preserve syntax** - do NOT change hoare triple syntax unless absolutely necessary
    - Think multiple times before modifying specs or code body
    - If changes are needed, decompose complex specs rather than rewriting

### Compilation Verification

- **After EVERY theorem:** Run `mcp` (preferred) or `lake build xxx`
- **Definition of complete:** NO errors or 'pure true' statements
- **Never mark as complete if:**
    - Any errors or 'pure true' statements remain
    - Compilation returns errors
    - Sorry is allowed, but only as a placeholder for the proof


### Important Notes

- Use MCP tool instead of bash command to get diagnostic messages!
- Skip already-imported theorems!! There might be warnings be just leave them there!
- You can use exisiting (and proved) theorem to assist your spec writing. If a theorem is necessary but not introduced, you can turn to work on that first. The useful theorems might not be in the same file, but in the import list
- When you are trying to use a certain lemma, check through mcp tools (or https://github.com/leanprover-community/mathlib4) to make sure the lemma exists. Else, write your own implementation of the lemma.

### Success Criteria

✅ All error and 'pure true' statements eliminated
✅ Clean compilation for entire file
✅ Each theorem verified individually before moving on
EOF

log_name=/Users/louhantao/Desktop/code/semester_6.5/FloatSpec/.log/codex_log/import_missing_theorems_${file}_round_2.log
# Build the CLI command as an array to preserve spaces/newlines
codex exec "$msg" --dangerously-bypass-approvals-and-sandbox | tee "$log_name"

done

for file in "${file_list[@]}"; do
IFS= read -r -d '' msg <<'EOF' || true
Please ensure your implementation Always Works™ for:

## Task: Introduce Missing Theorems in FloatSpec/src/Core/${file}

## Scope

Introduce missing theorems in the file. You can find the record of missing theorems in file /Users/louhantao/Desktop/code/semester_6.5/FloatSpec/FloatSpec/src/Core/Core_Theorems_Comparison.md, which is generated by comparing the Coq and Lean versions of the file. For all the missing theorems in the file, find their corresponding Coq implementation in /Users/louhantao/Desktop/code/semester_6.5/flocq/src/Core and implement them in Lean, using the same name and similar syntax with existing theorems. Leave the proofs empty for now.

### Prerequisites

1. **Read documentation first:**
    - FloatSpec/PIPELINE.md - understand the overall pipeline
    - ./CLAUDE.md - focus on proof writing instructions and mvcgen info

### Core Requirements

### Theorem Importing Process

1. **Follow the Zfast_div_eucl_spec example** in Zaux.lean and other theorems in current file as your template
2. **ONE-BY-ONE approach is mandatory:**
    - Write ONE theorem
    - Use the hoare triple syntax (introduced in FloatSpec/PIPELINE.md and CLAUDE.md) to write the theorem
    - Check immediately with mcp tool or `lake build`
    - Fix any errors before proceeding to next theorem
    - Never batch multiple theorems without checking
3. After writing each theorem, check whether they are aligned with the Coq implementation. If so, mark them as complete in the record file.

### Before Writing Each Theorem

1. **Verify function implementation** - ensure the function body is correct
2. **Preserve syntax** - do NOT change hoare triple syntax unless absolutely necessary
    - Think multiple times before modifying specs or code body
    - If changes are needed, decompose complex specs rather than rewriting

### Compilation Verification

- **After EVERY theorem:** Run `mcp` (preferred) or `lake build xxx`
- **Definition of complete:** NO errors or 'pure true' statements
- **Never mark as complete if:**
    - Any errors or 'pure true' statements remain
    - Compilation returns errors
    - Sorry is allowed, but only as a placeholder for the proof


### Important Notes

- Use MCP tool instead of bash command to get diagnostic messages!
- Skip already-imported theorems!! There might be warnings be just leave them there!
- You can use exisiting (and proved) theorem to assist your spec writing. If a theorem is necessary but not introduced, you can turn to work on that first. The useful theorems might not be in the same file, but in the import list
- When you are trying to use a certain lemma, check through mcp tools (or https://github.com/leanprover-community/mathlib4) to make sure the lemma exists. Else, write your own implementation of the lemma.

### Success Criteria

✅ All error and 'pure true' statements eliminated
✅ Clean compilation for entire file
✅ Each theorem verified individually before moving on
EOF

log_name=/Users/louhantao/Desktop/code/semester_6.5/FloatSpec/.log/codex_log/import_missing_theorems_${file}_round_3.log
# Build the CLI command as an array to preserve spaces/newlines
codex exec "$msg" --dangerously-bypass-approvals-and-sandbox | tee "$log_name"

done

# end=$(( $(date +%s) + 1*60*60 )); while [ "$(date +%s)" -lt "$end" ]; do claude -p "$msg" --verbose --dangerously-skip-permissions || true; done